language: python
sudo: required

matrix:
  include:
    - dist: xenial
      python: 3.6
      env: dist="16.04 LTS xenial"

before_install:
- sudo apt-get update -qq

install:
- ./dependencies.sh
- sudo -H pip3 install flake8 pylint
- git clone https://github.com/mininet/mininet
- PYTHON=python3 mininet/util/install.sh -nv

script:
- make
- sudo -E make codecheck  # terrible but mininet == sudo
# temporary: install patched faucet
- git clone https://github.com/lantz/faucet -b config_applied
- (cd faucet; sudo -H python3 setup.py install)
- sudo -E make test

notifications:
  email:
    on_success: never
