language: python
sudo: required

matrix:
  include:
    - dist: xenial
      python: 3.6
      env: dist="16.04 LTS xenial"

before_install:
- sudo apt-get update -qq

install:
- ./dependencies.sh
- ./test-dependencies.sh

script:
- make
- make codecheck
- ./faucetagent.py --version
- sudo make test

notifications:
  email:
    on_success: never
