language: python
sudo: required

matrix:
  include:
    - dist: xenial
      python: 3.6
      env: dist="16.04 LTS xenial"

before_install:
- sudo apt-get update -qq

install:
- ./dependencies.sh
- ./test-dependencies.sh
- echo "Testing against latest FAUCET"
- sudo pip3 -q install git+https://github.com/faucetsdn/faucet

script:
- make
- make codecheck
- sudo -E make test

notifications:
  email:
    on_success: never
